version: '3.9'

services:

  opensips:
    image: opensips:${TAG:-v1.0.0}
    build:
        dockerfile: Dockerfile.opensips
    container_name: opensips
    restart: unless-stopped
    hostname: opensips
    ports:
    - "5060:5060/udp"
    - "5060:5060/tcp"
    #stdin_open: true
    #tty: true
    #command: bash

volumes:
  pgdata:

