version: '3.9'

services:

  freeswitch:
    container_name: freeswitch
    privileged: yes
    ulimits:
      rtprio: 99
    env_file:
      - deploy/variables.env
    #stdin_open: true
    #tty: true
    #command: bash
    image: freeswitch:0.0.1
    networks:
      customnetwork:
        ipv4_address: 172.20.0.10
    
networks:
  customnetwork:
    ipam:
      config:
      - subnet: 172.20.0.0/16
